

<html>
    <?php
    $total = 0;
    $sino = 1;
    $gTotal = 0;
    $isFirst = TRUE;
    ?>
    <head>

        <style>   
            tr:nth-child(odd)		
            { background-color:#FFFFFF; }
            tr:nth-child(even)		
            { background-color:#e8f6f3; }
            table2{
                font-size: 12px;
                font-weight: bold;
                font-color: #E91E63;
            }
            tr{

                font-weight: bold;
                height: 15px;
                vertical-align: middle;
            }
            tr.header > td 
            {
                font-weight: bold;
                color: #4CAF50;
                background-color: #4CAF50;
                height: 15px;
                /*vertical-align: middle;*/
                font-family: "Times New Roman", Times, serif;
            }
            /*            table.tableH
                        {
                            border-top: 1px solid #641E16;
                            border-bottom: 1px solid #641E16;
                        }*/
            table.table2 td.col1
            {
                /*width:20%;*/
                text-align: left;
            }
            table.table2 td.col2
            {
                /*width:40%;*/
                text-align: left
            }
            table.table2 td.col3
            {
                /*width:40%;*/
                text-align: right;        
            }
            table.table2 td.colU
            {
                border-top: 0.1px solid #4CAF50;
            }

            p.line
            {
                font-size: 2px;
                font-weight: normal;
            }
            h4 {
                text-align: center;
            }
        </style>
        <title><?php echo $title; ?></title>
    </head>


    <body>
        <div style="text-align: center; padding-bottom:5px; display: block; height:60px;">
            <img src="<?php echo base_url('assets/theme/img/report/3.jpg'); ?>" alt="Techno Aliance" style="height: 40px;padding-top: 0px;" />
            <p>
                P.O Box :22628, Ajman - UAE
                <br />
                technoalliancetrading@gmail.com</p>
        </div>
        <h4 style="padding-top:5px;"> <?php echo $title; ?></h4>
        <p class="line">&nbsp;</p>
        <p>Date : 12 - Dec - 2017 to 20 - Dec - 2017 <br/>
        Bookstore Stock summary report for Main Store, Dubai <br/>
        Report generated by Dhanya R.G</p>

        <table  class="table2 tableH" cellpadding="2" width="100%" style="font-family:Times New Roman, Georgia, Serif; padding:0px 0 0 0;" >
            <thead>

                <tr class="header">
                    <td class="col1" bgcolor="#4CAF50" width="2px" align="center"><font color="#FCFEFC" ><h3>SNo</h3></td>
                    <td class="col2" bgcolor="#4CAF50" width="2px" align="center"><font color="#FCFEFC" ><h3>Item Name</h3></td>
                    <td class="col3" bgcolor="#4CAF50" width="2px" align="center"><font color="#FCFEFC" ><h3>Edition</h3></td>
                    <td class="col3" bgcolor="#4CAF50" width="2px" align="center"><font color="#FCFEFC" ><h3>Opening Stock</h3></td>
                    <td class="col3" bgcolor="#4CAF50" width="10%" align="center"><font color="#FCFEFC" ><h3>Purchase Qty</h3></td>
                    <td class="col3" bgcolor="#4CAF50" width="10%" align="center"><font color="#FCFEFC" ><h3>Sale Ret Qty</h3></td>
                    <td class="col3" bgcolor="#4CAF50" width="10%" align="center"><font color="#FCFEFC" ><h3>Transfer In</h3></td>
                    <td class="col3" bgcolor="#4CAF50" width="10%" align="center"><font color="#FCFEFC" ><h3>Spec Ret</h3></td>
                    <td class="col3" bgcolor="#4CAF50" width="10%" align="center"><font color="#FCFEFC" ><h3>Purchase Return</h3></td>
                    <td class="col3" bgcolor="#4CAF50" width="10%" align="center"><font color="#FCFEFC" ><h3>Sale Qty</h3></td>
                    <td class="col3" bgcolor="#4CAF50" width="10%" align="center"><font color="#FCFEFC" ><h3>Transfer Out</h3></td>
                    <td class="col3" bgcolor="#4CAF50" width="10%" align="center"><font color="#FCFEFC" ><h3>Spec Qty</h3></td>
                    <td class="col3" bgcolor="#4CAF50" width="10%" align="center"><font color="#FCFEFC" ><h3>Closing Stock</h3></td>
                </tr>
            </thead>
            <tbody>
                <?php
                if (isset($report_data) && !empty($report_data)) {
                    $i = 1;
                    foreach ($report_data as $key => $data) {
                        ?>
                        <tr>
                            <td colspan="13">Item Type : <?php echo $data['type_data']['type_name']; ?></td>
                        </tr>
                        <?php
                        if (isset($data['items']) && !empty($data['items']) ) {
                            foreach ($data['items'] as $items) {
                                ?>
                                <tr>
                                    <td width="2px"  align="center"><?php echo $i; ?></td>
                                    <td width="2px" align="left"><?php echo $items['item_data']['item_name']; ?></td>
                                    <td width="2px"  align="center"><?php echo $items['item_data']['edition_name']; ?></td>
                                    <td width="2px"  align="center"><?php echo $items['stock_data']['opening_balance']; ?></td>
                                    <td width="2px"  align="center"><?php echo $items['stock_data']['purchase']; ?></td>
                                    <td  align="center"><?php echo $items['stock_data']['sale_return']; ?></td>
                                    <td  align="center"><?php echo $items['stock_data']['transfer_in']; ?></td>
                                    <td  align="center"><?php echo $items['stock_data']['spec_return']; ?></td>
                                    <td  align="center"><?php echo $items['stock_data']['purchase_return']; ?></td>
                                    <td  align="center"><?php echo $items['stock_data']['sale']; ?></td>
                                    <td  align="center"><?php echo $items['stock_data']['transfer_out']; ?></td>
                                    <td  align="center"><?php echo $items['stock_data']['spec_issue']; ?></td>
                                    <td  align="center"><?php echo $items['stock_data']['closing_stock']; ?></td>
                                </tr>
                                <?php
                                $i++;
                            }
                        }
                        ?>
                        <tr>
                            <td colspan="3" align="right">Sub Total : </td>
                            <td  align="center"><?php echo $data['type_summary']['opening_balance']; ?></td>
                            <td align="center"><?php echo $data['type_summary']['purchase']; ?></td>
                            <td  align="center"><?php echo $data['type_summary']['sale_return']; ?></td>
                            <td align="center"><?php echo $data['type_summary']['transfer_in']; ?></td>
                            <td  align="center"><?php echo $data['type_summary']['spec_return']; ?></td>
                            <td  align="center"><?php echo $data['type_summary']['purchase_return']; ?></td>
                            <td  align="center"><?php echo $data['type_summary']['sale']; ?></td>
                            <td  align="center"><?php echo $data['type_summary']['transfer_out']; ?></td>
                            <td  align="center"><?php echo $data['type_summary']['spec_issue']; ?></td>
                            <td  align="center"><?php echo $data['type_summary']['closing_stock']; ?></td>
                        </tr>
                    <?php }
                    ?>
                    <tr>
                        <td colspan="3" align="right">Grand Total</td>
                        <td  align="center"><?php echo $grand_total_data['opening_balance']; ?></td>
                        <td align="center"><?php echo $grand_total_data['purchase']; ?></td>
                        <td  align="center"><?php echo $grand_total_data['sale_return']; ?></td>
                        <td align="center"><?php echo $grand_total_data['transfer_in']; ?></td>
                        <td  align="center"><?php echo $grand_total_data['spec_return']; ?></td>
                        <td  align="center"><?php echo $grand_total_data['purchase_return']; ?></td>
                        <td  align="center"><?php echo $grand_total_data['sale']; ?></td>
                        <td  align="center"><?php echo $grand_total_data['transfer_out']; ?></td>
                        <td  align="center"><?php echo $grand_total_data['spec_issue']; ?></td>
                        <td  align="center"><?php echo $grand_total_data['closing_stock']; ?></td>
                    </tr>
                <?php }
                ?>
            </tbody>
        </table>
<!--        <table class="table2" cellsapcing="0" cellpadding="0" style="font-family:Times New Roman, Georgia, Serif;"  style="font-size: 11px" width="100%">

            <tr class="header">
                <td class="col1"> </td>
                <td class="col2"> </td>
                <td class="col3 colU">
                    <div font-color="#e9f7ef"><h5>Total : <?php echo $total; ?></h5></div>
                </td>
            </tr>
            <tr class="header" font-weight="bold">
                <td class="col1"> </td>
                <td class="col2"> </td>
                <td class="col3 colU">
                    <div font-color="#e9f7ef" style="font-size: 13px"><h5>Grand Total : <?php echo ($gTotal + $total); ?></h5></div>
                </td>
            </tr>


        </table>-->
    </body>

</html>
