<script>
Found 496 matches of   function  in 98 files. To be replaced with   function uniform_.	
add_allotment_sub_out.php	
    function activate_toast_message(message, title, type) {      [position 179:3]	
    function submit_allotment() {      [position 200:3]	
    function select_item(item_id, item_name, itemtype_name, item_code, barcode, selling_price, rate, stock) {      [position 353:3]	
    function valuedisplay(item_id, price, stock) {      [position 406:3]	
    function deletedisplay(item_id) {      [position 469:3]	
    function search_item() {      [position 544:3]	
edit_allotment_out.php	
    function activateSwitchery() {      [position 227:3]	
    function select_item(item_id, item_name, item_code, barcode, selling_price, rate, ava_stock) {      [position 254:3]	
    function valuedisplay(item_id) {      [position 307:3]	
    function deletedisplay(item_id) {      [position 366:3]	
    function search_item() {      [position 448:3]	
    function save_edit_allotment() {      [position 465:3]	
show_allotment_out_list.php	
//    function add_new_allotment_substore() {      [position 107:5]	
     function add_new_allotment_substore() {      [position 123:4]	
//    function edit_allotment() {      [position 140:5]	
    function edit_allotment(allotment_id) {      [position 158:3]	
    function view_allotment(allotment_id) {      [position 204:3]	
//    function view_allotment() {      [position 251:5]	
    function approve_allotment(allotment_id) {      [position 266:3]	
    function discard_allotment(allotment_id) {      [position 311:3]	
veiw_allotment_sub_out.php	
    function activateSwitchery() {      [position 237:3]	
    function select_item(item_id, item_name, item_code, selling_price, barcode) {      [position 264:3]	
    function valuedisplay(item_id, selling_price) {      [position 312:3]	
advancedstudentfilter_view.php	
    function show_search() {      [position 118:3]	
    function hide_search() {      [position 121:3]	
    function search_name(acdyr_id, batch_id) {      [position 126:3]	
bill_history.php	
    function toggle_country_add() {      [position 124:3]	
    function change_status(country_id, element) {      [position 138:3]	
    function submit_data() {      [position 226:3]	
    function submit_edit_save_data() {      [position 351:3]	
    function refresh_add_panel() {      [position 477:3]	
    function bill_detail1() {      [position 487:3]	
    function close_add_country() {      [position 519:3]	
     function bill_detail() {      [position 528:4]	
bill_view_details.php	
    function print_bill(billid) {      [position 161:3]	
    function print_bill_demo(billid) {      [position 165:3]	
    function cancel_bill(billid) {      [position 169:3]	
    function submit_uniform_bill_cancel(billid) {      [position 172:3]	
billtest.php	
                                function search_name() {      [position 173:31]	
                                function searchadvance_filtername() {      [position 207:31]	
                                function changed_class1111() {      [position 246:31]	
                                function changed_class() {      [position 274:31]	
pack_details_view.php	
    function apply_discount(item_id, sub_total, vat) {      [position 390:3]	
    function remove_discount(item_id, sub_total, vat) {      [position 505:3]	
    function cash_pay() {      [position 618:3]	
    function cheque_pay() {      [position 720:3]	
    function card_pay() {      [position 866:3]	
pack_details_view_bak_before_discount_add.php	
    function cash_pay() {      [position 567:3]	
    function cheque_pay() {      [position 647:3]	
    function card_pay() {      [position 760:3]	
    function change_valuedisplay() {      [position 869:3]	
profile_search_result.php	
    function bill_detail(studentid) {      [position 90:3]	
show_settings.php	
    function simpleLoad(btn, state) {      [position 80:3]	
    function load_graph() {      [position 91:3]	
    function load_supplier() {      [position 106:3]	
                function activateSwitchery() {      [position 141:15]	
   function load_student_sale() {      [position 158:2]	
   function deliveryreturn() {      [position 171:2]	
//   function deliveryreturn() {      [position 184:4]	
   function load_employee_sales() {      [position 197:2]	
    function load_specimen_issue() {      [position 210:3]	
    function load_items_list() {      [position 223:3]	
//    function load_sale() {      [position 236:5]	
    function load_sale() {      [position 249:3]	
    function load_ohtemplate() {      [position 276:3]	
    function load_template() {      [position 289:3]	
    function load_opening_stock() {      [position 302:3]	
    function load_transfer_rqst() {      [position 315:3]	
    function stocktransfer_list() {      [position 332:3]	
    function stocktransfer() {      [position 345:3]	
    function livestock() {      [position 358:3]	
    function student_bill(){      [position 371:3]	
    function employee_bill(){      [position 384:3]	
    function bill_history(){      [position 397:3]	
    function bill_test(){      [position 410:3]	
    function load_ohitempacking() {      [position 424:3]	
    function load_batchpacking() {      [position 437:3]	
    function load_classpacking() {      [position 450:3]	
    function load_specimenpacking() {      [position 463:3]	
    function load_ohitemissue() {      [position 476:3]	
    function load_ohitemgroupissue() {      [position 489:3]	
     function load_specimen_issue() {      [position 502:4]	
    function item_packing_sale() {      [position 515:3]	
    function individual_loose_pack() {      [position 528:3]	
    function load_delivery() {      [position 541:3]	
    function load_itemadd() {      [position 554:3]	
student_bill.php	
    function select_items(id) {      [position 102:3]	
    function search_item() {      [position 131:3]	
//     function select_itemsss(id) {alert(id)       ;      [position 198:6]	
studentbill.php	
    function select_bill(billid, billcode) {      [position 128:3]	
    function select_items(id, barcode) {      [position 150:3]	
    function search_item() {      [position 174:3]	
//     function select_itemsss(id) {alert(id)       ;      [position 243:6]	
advancedstudentfilter_view.php	
    function show_search() {      [position 118:3]	
    function hide_search() {      [position 121:3]	
    function search_name(acdyr_id, batch_id) {      [position 126:3]	
delivery_emp_search.php	
     function emp_search_data() {      [position 104:4]	
    function specimen_delivery(Emp_id) {      [position 132:3]	
delivery_faculty_search.php	
    function oh_bill() {      [position 137:3]	
    function specimen_packing_bak() {      [position 151:3]	
    function delivery_faculty(Emp_id) {      [position 165:3]	
    function other_bill() {      [position 194:3]	
//     function oh_bill(studentid) {      [position 208:6]	
    function edit_profile(studentid) {      [position 222:3]	
    function send_personal_email(student_id, acd_id, batchid) {      [position 251:3]	
    function profile_detail(studentid) {      [position 292:3]	
    function fees_detail(studentid) {      [position 310:3]	
    function show_search() {      [position 329:3]	
    function hide_search() {      [position 332:3]	
    function search_name() {      [position 337:3]	
delivery_onvoucher_search.php	
    function student_select_items(packet_id, student_id) {      [position 59:3]	
    function select_items_delivery(id) {      [position 63:3]	
    function bill_detail_delivery(studentid) {      [position 93:3]	
    function select_items(id) {      [position 121:3]	
    function search_item() {      [position 154:3]	
    //     function select_itemsss(id) {alert(id)       ;      [position 224:10]	
delivery_rtrn_empsearch.php	
     function emp_search_data() {      [position 74:4]	
delivery_rtrn_stsearch.php	
     function st_search_data() {      [position 201:4]	
    function load_students_after_filter(batchid, acd_yr = 0) {      [position 230:3]	
delivery_rtrnsearch.php	
     function load_st_search() {      [position 35:4]	
     function load_emp_search() {      [position 62:4]	
     function close_advance_search() {      [position 89:4]	
    function refresh_add_panel() {      [position 96:3]	
delivery_st_search.php	
     function st_search_data() {      [position 95:4]	
delivery_student_search.php	
                                    function search_name() {      [position 210:35]	
                                    function search_voucher() {      [position 246:35]	
                                    function searchadvance_filtername() {      [position 278:35]	
                                    function changed_class1111() {      [position 318:35]	
                                    function changed_class() {      [position 347:35]	
dlivery_pack_items.php	
    function replace_item(del_detail_id, item_id, price, type_id, qty, pending_qty) {      [position 176:3]	
    function submit_data(delivery_id, delivery_number) {      [position 213:3]	
    function print_data(delivery_id) {      [position 313:3]	
    function replace_OH(template_config_id, template_id) {      [position 345:3]	
dlivery_replace_items.php	
    function replaced_item(item_id) {      [position 104:3]	
    function close_replace(){      [position 169:3]	
    function select_items_delivery(id) {      [position 175:3]	
faculty_delivery.php	
    function select_items(id) {      [position 112:3]	
   function search_faculty_voucher() {      [position 147:2]	
item_loosedelivery.php	
    function submit_data() {      [position 194:3]	
    function add_list(item_code, item_name, itemtype_name, price, item_id) {      [position 271:3]	
    function valuedisplay(item_id, price) {      [position 314:3]	
    function deletedisplay(item_id, price) {      [position 403:3]	
    function search_item() {      [position 495:3]	
profile.php	
    function edit_profile(studentid) {      [position 151:3]	
    function send_personal_email(student_id, acd_id, batchid) {      [position 180:3]	
    function profile_detail(studentid) {      [position 221:3]	
    function fees_detail(studentid) {      [position 239:3]	
    function show_search() {      [position 258:3]	
    function hide_search() {      [position 261:3]	
    function search_name(acdyr_id, batch_id) {      [position 266:3]	
    function loose_packing(std_id) {      [position 292:3]	
     function loose_delivery(std_id) {      [position 313:4]	
profile_search_result.php	
    function bill_detail_delivery(studentid) {      [position 56:3]	
specimen_delivery.php	
    function submit_data() {      [position 162:3]	
    function add_list(item_code, item_name, itemtype_name, price, item_id) {      [position 239:3]	
    function valuedisplay(item_id, price) {      [position 282:3]	
    function deletedisplay(item_id, price) {      [position 369:3]	
    function search_item() {      [position 461:3]	
student_delivery.php	
    function select_items_delivery(id) {      [position 123:3]	
    function search_item(student_id) {      [position 157:3]	
//     function select_itemsss(id) {alert(id)       ;      [position 229:6]	
student_delivery_onvoucher_search.php	
    function select_items_delivery(id) {      [position 62:3]	
deliveryReturn_faculty_search.php	
    function oh_bill() {      [position 136:3]	
    function specimen_packing_bak() {      [position 150:3]	
    function delivery_return_faculty(Emp_id) {      [position 164:3]	
    function other_bill() {      [position 193:3]	
//     function oh_bill(studentid) {      [position 207:6]	
    function edit_profile(studentid) {      [position 221:3]	
    function send_personal_email(student_id, acd_id, batchid) {      [position 250:3]	
    function profile_detail(studentid) {      [position 291:3]	
    function fees_detail(studentid) {      [position 309:3]	
    function show_search() {      [position 328:3]	
    function hide_search() {      [position 331:3]	
    function search_name() {      [position 336:3]	
deliveryReturn_student_search.php	
                                function search_name() {      [position 207:31]	
                                function search_voucher() {      [position 240:31]	
                                function searchadvance_filtername() {      [position 273:31]	
                                function changed_class1111() {      [position 318:31]	
                                function changed_class() {      [position 347:31]	
delivery_pack_items_OH.php	
    function return_item(del_detail_id, item_id, price, type_id, qty, delivery_qty, available_qty, tax_percent, tax_type) {      [position 454:3]	
    function submit_data(delivery_id, delivery_number) {      [position 596:3]	
    function submit_data_OH(delivery_id, delivery_number) {      [position 669:3]	
dlivery_pack_items.php	
    function return_item(del_detail_id, item_id, price, type_id, qty, delivery_qty, available_qty, tax_percent, tax_type) {      [position 419:3]	
    function submit_data(delivery_id, delivery_number) {      [position 563:3]	
    function submit_data_OH(delivery_id, delivery_number) {      [position 638:3]	
faculty_deliveryReturn.php	
    function select_items(id) {      [position 110:3]	
     function search_faculty_delivery_return() {      [position 141:4]	
//     function select_itemsss(id) {alert(id)       ;      [position 213:6]	
faculty_dlivery_pack_items.php	
    function return_item(item_id, price, type_id, qty, delivery_qty, available_qty, tax_percent, tax_type) {      [position 284:3]	
    function submit_data(delivery_id, delivery_number) {      [position 436:3]	
profile_search_result.php	
    function bill_detail(studentid) {      [position 57:3]	
student_deliveryReturn.php	
    function select_items(id) {      [position 112:3]	
    function search_item(student_id) {      [position 143:3]	
//     function select_itemsss(id) {alert(id)       ;      [position 215:6]	
student_deliveryReturn_onvoucher_search.php	
                                    function select_items_delivery_return(packid, student_id) {      [position 56:35]	
                                    function select_items(id) {      [position 60:35]	
                                    function bill_detail(studentid) {      [position 91:35]	
                                    function select_items(id) {      [position 121:35]	
                                    function search_item() {      [position 155:35]	
OH_item.php	
    function openhouse() {      [position 139:3]	
    function item_confirm() {      [position 177:3]	
    function confirm_item_close() {      [position 184:3]	
    function temp_confirm() {      [position 193:3]	
    function temp_confirm_2() {      [position 200:3]	
    function item_close() {      [position 208:3]	
    function item_close_2() {      [position 215:3]	
    function student_assignment(openhouse_id, template_id) {      [position 253:3]	
    function toggleVisibility(divId) {      [position 287:3]	
    function hideNonVisibleDivs() {      [position 295:3]	
OH_packing.php	
    function item_confirm() {      [position 135:3]	
    function confirm_item_close() {      [position 142:3]	
    function temp_confirm() {      [position 151:3]	
    function temp_confirm_2() {      [position 158:3]	
    function item_close() {      [position 166:3]	
    function item_close_2() {      [position 173:3]	
    function search_template() {      [position 218:3]	
    function items_add(id, name) {      [position 245:3]	
    function toggleVisibility(divId) {      [position 261:3]	
    function hideNonVisibleDivs() {      [position 269:3]	
Ohpack_itemadd.php	
    function   add_to_list() {      [position 229:3]	
    function search_item() {      [position 302:3]	
    function add_list(item_code, barcode, itemtype_name, price, item_id, tax_type, tax_value) {      [position 332:3]	
    function valuedisplay(item_id, price, tax_type, tax_value) {      [position 383:3]	
    function deletedisplay(item_id, price, tax_type, tax_value) {      [position 513:3]	
    function change_valuedisplay() {      [position 643:3]	
    function submit_data() {      [position 692:3]	
Ohpack_itemadd_readd.php	
    function   add_to_list() {      [position 303:3]	
    function search_item() {      [position 376:3]	
    function add_list(item_code, barcode, itemtype_name, price, item_id, tax_type, tax_value) {      [position 406:3]	
    function valuedisplay(item_id, price, tax_type, tax_value) {      [position 457:3]	
    function deletedisplay(item_id, price, tax_type, tax_value) {      [position 586:3]	
    function change_valuedisplay() {      [position 718:3]	
    function submit_data() {      [position 769:3]	
add_new_temp_openhouse.php	
    function submit_add_new_temps(master_id) {      [position 132:3]	
edit_openhouse.php	
    function submit_edit_data(master_id) {      [position 226:3]	
item_delivery.php	
     function load_st_search() {      [position 35:4]	
     function load_emp_search() {      [position 62:4]	
     function close_advance_search() {      [position 89:4]	
    function refresh_add_panel() {      [position 96:3]	
list_openhouse.php	
    function add_openhouse() {      [position 165:3]	
    function uniform_edit_openhouse(id) {      [position 179:3]	
    function add_temp_openhouse(id) {      [position 193:3]	
    function view_openhouse(id) {      [position 207:3]	
    function uniform_delete_openhouse(id, description) {      [position 221:3]	
newohtemplate.php	
    function submit_data() {      [position 120:3]	
    function submit_edit_save_data() {      [position 245:3]	
    function refresh_add_panel() {      [position 371:3]	
    function edit_country(countryid, name, code, nation, currency) {      [position 381:3]	
    function close_add_country() {      [position 413:3]	
    function add_new_country() {      [position 422:3]	
oh_stud_assign.php	
                                            function item_list() {      [position 377:43]	
                                            function load_batch_data() {      [position 453:43]	
                                            function search_student() {      [position 482:43]	
                                            function save_data() {      [position 552:43]	
oh_template.php	
    function submit_data() {      [position 103:3]	
    function submit_edit_data() {      [position 168:3]	
    function refresh_add_panel() {      [position 234:3]	
    function edit_ohtemplate(id, name, description) {      [position 241:3]	
    function close_add_ohtemplate() {      [position 264:3]	
    function add_new_template() {      [position 273:3]	
openhouse.php	
    function submit_data() {      [position 204:3]	
openhouse_change.php	
    function item_confirm() {      [position 155:3]	
    function confirm_item_close() {      [position 162:3]	
    function temp_confirm() {      [position 171:3]	
    function temp_confirm_2() {      [position 178:3]	
    function item_close() {      [position 186:3]	
    function item_close_2() {      [position 193:3]	
    function list_student_assigned(openhouse_id, template_id, flag) {      [position 239:3]	
     function close_stud_allocation() {      [position 271:4]	
    function submit_openhouse_remove() {      [position 303:3]	
    function toggleVisibility(divId) {      [position 366:3]	
    function hideNonVisibleDivs() {      [position 374:3]	
    function openhouse() {      [position 396:3]	
openhouse_view.php	
    function item_confirm() {      [position 148:3]	
    function confirm_item_close() {      [position 155:3]	
    function temp_confirm() {      [position 164:3]	
    function temp_confirm_2() {      [position 171:3]	
    function item_close() {      [position 179:3]	
    function item_close_2() {      [position 186:3]	
    function list_student_assigned(openhouse_id, template_id) {      [position 232:3]	
    function close_stud_allocation() {      [position 260:3]	
    function toggleVisibility(divId) {      [position 296:3]	
    function hideNonVisibleDivs() {      [position 304:3]	
    function openhouse() {      [position 326:3]	
profile.php	
     function oh_bill() {      [position 144:4]	
//     function oh_bill(studentid) {      [position 158:6]	
    function edit_profile(studentid) {      [position 172:3]	
    function send_personal_email(student_id, acd_id, batchid) {      [position 201:3]	
    function profile_detail(studentid) {      [position 242:3]	
    function fees_detail(studentid) {      [position 260:3]	
    function show_search() {      [position 279:3]	
    function hide_search() {      [position 282:3]	
    function search_name(acdyr_id, batch_id) {      [position 287:3]	
student_filter.php	
    function load_students_after_filter(batchid, acd_yr = 0) {      [position 180:3]	
    function search_student() {      [position 206:3]	
view_openhouse.php	
    function submit_edit_data(master_id) {      [position 183:3]	
item_batchpacking.php	
    function batch_list1(class_id) {      [position 105:3]	
item_classpacking.php	
    function batch_list1(class_id) {      [position 151:3]	
    function batch_list(class_id) {      [position 164:3]	
    function load_students_after_filter(class_id, acd_yr = 0) {      [position 179:3]	
    function search_name(acdyr_id) {      [position 215:3]	
item_loosepacking.php	
    function   add_to_list() {      [position 162:3]	
    function activate_toast_message(message, title, type) {      [position 177:3]	
    function submit_data() {      [position 198:3]	
    function add_list(item_code, item_name, itemtype_name, price, item_id, tax_type, tax_value) {      [position 287:3]	
    function valuedisplay(item_id, price, tax_type, tax_value) {      [position 331:3]	
    function deletedisplay(item_id, price, tax_type, tax_value) {      [position 425:3]	
    function search_item() {      [position 509:3]	
item_specimenpacking.php	
    function   add_to_list() {      [position 171:3]	
    function activate_toast_message(message, title, type) {      [position 187:3]	
    function submit_data() {      [position 208:3]	
    function add_list(item_code, item_name, itemtype_name, price, item_id, tax_type, tax_value) {      [position 315:3]	
    function valuedisplay(item_id, price, tax_type, tax_value) {      [position 359:3]	
    function deletedisplay(item_id, price, tax_type, tax_value) {      [position 458:3]	
    function search_item() {      [position 537:3]	
profile.php	
    function edit_profile(studentid) {      [position 149:3]	
    function send_personal_email(student_id, acd_id, batchid) {      [position 178:3]	
    function profile_detail(studentid) {      [position 219:3]	
    function fees_detail(studentid) {      [position 237:3]	
    function show_search() {      [position 256:3]	
    function hide_search() {      [position 259:3]	
    function search_name(acdyr_id, batch_id) {      [position 264:3]	
    function loose_packing(std_id) {      [position 290:3]	
search_student.php	
    function loose_packing(std_id) {      [position 63:3]	
billed_but_not_delivered.php	
        function submit_data() {      [position 67:7]	
collection_report.php	
        function submit_data() {      [position 67:7]	
collection_report_user_wise.php	
        function submit_data() {      [position 67:7]	
return_report.php	
        function submit_data() {      [position 76:7]	
sale_report.php	
        function submit_data() {      [position 67:7]	
sale_report_item.php	
        function submit_data() {      [position 77:7]	
sale_report_item_summary.php	
        function submit_data() {      [position 77:7]	
stock_report_detail.php	
        function submit_data() {      [position 67:7]	
stock_report_summary.php	
        function submit_data() {      [position 67:7]	
item_empl_search.php	
                                                    function get_emp_code() {      [position 366:51]	
                                                    function emp_close() {      [position 374:51]	
                                                    function item_close_2() {      [position 381:51]	
                                                    function get_filter() {      [position 388:51]	
                                                    function filter_close() {      [position 395:51]	
                                                    function show_invoice() {      [position 401:51]	
item_employee_search.php	
     function emp_search_data() {      [position 85:4]	
item_individualpack.php	
     function st_search_data() {      [position 99:4]	
item_packing.php	
     function load_st_search() {      [position 35:4]	
     function load_emp_search() {      [position 62:4]	
     function close_advance_search() {      [position 89:4]	
    function refresh_add_panel() {      [position 96:3]	
item_student_search.php	
     function st_search_data() {      [position 98:4]	
profile.php	
     function oh_bill() {      [position 144:4]	
     function other_bill() {      [position 158:4]	
//     function oh_bill(studentid) {      [position 172:6]	
    function edit_profile(studentid) {      [position 186:3]	
    function send_personal_email(student_id, acd_id, batchid) {      [position 215:3]	
    function profile_detail(studentid) {      [position 256:3]	
    function fees_detail(studentid) {      [position 274:3]	
    function show_search() {      [position 293:3]	
    function hide_search() {      [position 296:3]	
    function search_name(acdyr_id, batch_id) {      [position 301:3]	
profile_staff.php	
    function oh_bill() {      [position 143:3]	
    function specimen_packing_bak() {      [position 157:3]	
    function specimen_packing(Emp_id) {      [position 171:3]	
    function other_bill() {      [position 191:3]	
//     function oh_bill(studentid) {      [position 205:6]	
    function edit_profile(studentid) {      [position 219:3]	
    function send_personal_email(student_id, acd_id, batchid) {      [position 248:3]	
    function profile_detail(studentid) {      [position 289:3]	
    function fees_detail(studentid) {      [position 307:3]	
    function show_search() {      [position 326:3]	
    function hide_search() {      [position 329:3]	
    function search_name() {      [position 334:3]	
show_saleissue.php	
    function toggleVisibility(divId) {      [position 327:3]	
    function hideNonVisibleDivs() {      [position 335:3]	
specimen_item_purchase.php	
                                                    function get_emp_code() {      [position 595:51]	
                                                    function emp_close() {      [position 603:51]	
                                                    function item_close_2() {      [position 610:51]	
                                                    function get_filter() {      [position 617:51]	
                                                    function filter_close() {      [position 624:51]	
                                                    function show_invoice() {      [position 630:51]	
student_filter.php	
    function toggleVisibility(divId) {      [position 286:3]	
    function hideNonVisibleDivs() {      [position 294:3]	
student_sale.php	
                                                    function get_emp_code() {      [position 395:51]	
                                                    function emp_close() {      [position 403:51]	
                                                    function item_close_2() {      [position 410:51]	
                                                    function get_filter() {      [position 417:51]	
                                                    function filter_close() {      [position 424:51]	
                                                    function show_invoice() {      [position 430:51]	
show_settings.php	
    function delivery_student() {      [position 257:3]	
    function simpleLoad(btn, state) {      [position 274:3]	
    function load_graph() {      [position 285:3]	
    function load_supplier() {      [position 300:3]	
                function activateSwitchery() {      [position 335:15]	
    function load_student_sale() {      [position 352:3]	
    function deliveryreturn() {      [position 365:3]	
    function specimen_return() {      [position 381:3]	
//   function deliveryreturn() {      [position 397:4]	
    function load_employee_sales() {      [position 410:3]	
    function load_specimen_issue() {      [position 423:3]	
    function load_items_list() {      [position 436:3]	
    function load_sale() {      [position 450:3]	
    function load_ohtemplate() {      [position 477:3]	
    function specimen_delivery() {      [position 493:3]	
    function load_openhouse() {      [position 509:3]	
    function load_template() {      [position 525:3]	
    function load_opening_stock() {      [position 538:3]	
    function load_transfer_rqst() {      [position 551:3]	
    function stocktransfer_list() {      [position 568:3]	
    function stocktransfer() {      [position 581:3]	
    function livestock() {      [position 594:3]	
    function student_bill() {      [position 615:3]	
    function employee_bill() {      [position 628:3]	
    function bill_history() {      [position 641:3]	
    function bill_test() {      [position 654:3]	
    function load_ohitempacking() {      [position 668:3]	
    function load_batchpacking() {      [position 684:3]	
    function load_classpacking() {      [position 697:3]	
    function load_specimenpacking() {      [position 713:3]	
    function load_ohitemissue() {      [position 729:3]	
    function load_ohitemgroupissue() {      [position 742:3]	
    function load_specimen_issue() {      [position 758:3]	
    function item_packing_sale() {      [position 771:3]	
    function individual_loose_pack() {      [position 784:3]	
    function load_delivery() {      [position 797:3]	
    function load_itemadd() {      [position 810:3]	
    function create_template() {      [position 826:3]	
    function stock_allotment_list() {      [position 839:3]	
    function load_return_rpt() {      [position 857:3]	
    function load_sale_rpt() {      [position 873:3]	
    function load_sale_item_rpt() {      [position 889:3]	
    function load_sale_item_summary_rpt() {      [position 905:3]	
    function load_billed_not_delivered_rpt() {      [position 921:3]	
    function load_collection_rpt() {      [position 938:3]	
    function load_collection_userwise_rpt() {      [position 955:3]	
    function load_stock_detail_report() {      [position 972:3]	
    function load_stock_summary_report() {      [position 988:3]	
    function remove_student_allotment() {      [position 1006:3]	
    function stock_allotment_Outword() {      [position 1023:3]	
    function view_student_allotment() {      [position 1039:3]	
Ohpack_itemadd.php	
        function activateSwitchery() {      [position 364:7]	
        function select_item(item_id, itemtype_name, item_code, selling_price, barcode) {      [position 391:7]	
        function valuedisplay(item_id) {      [position 439:7]	
        function deletedisplay(item_id) {      [position 472:7]	
allotment_details_view.php	
    function activateSwitchery() {      [position 195:3]	
    function select_item(item_id, item_name, item_code, selling_price, barcode) {      [position 222:3]	
    function valuedisplay(item_id, selling_price) {      [position 270:3]	
edit_supplier.php	
        function toggle_edit_panel() {      [position 83:7]	
        function clear_controls() {      [position 91:7]	
items_add.php	
    function show_barcode(barcode) {      [position 240:3]	
show_allotment_list.php	
    function view_allotment(allotment_id) {      [position 105:3]	
show_supplier.php	
    function activateSwitchery() {      [position 63:3]	
    function toggle_country_add() {      [position 76:3]	
   function change_status(country_id, element) {      [position 90:2]	
    function submit_data() {       [position 175:3]	
   function submit_edit_save_data() {      [position 282:2]	
    function refresh_add_panel() {      [position 393:3]	
    function edit_country(countryid, name, code, currency) {      [position 401:3]	
    function close_add_country() {      [position 433:3]	
stock_manager.php	
                                                        function simpleLoad(btn, state) {      [position 81:55]	
                                                        function load_supplier() {      [position 93:55]	
                                                        function load_publisher() {      [position 108:55]	
                                                        function sale() {      [position 121:55]	
                                                        function load_district() {      [position 135:55]	
                                                        function load_religion() {      [position 148:55]	
                                                        function load_caste() {      [position 161:55]	
                                                        function load_community() {      [position 174:55]	
                                                        function load_currency() {      [position 187:55]	
                                                        function load_language() {      [position 200:55]	
                                                        function load_profession() {      [position 213:55]	
stock_transferintend.php	
        function toggleVisibility(divId) {      [position 274:7]	
        function hideNonVisibleDivs() {      [position 282:7]	
edit_supplier.php	
        function toggle_edit_panel() {      [position 83:7]	
        function clear_controls() {      [position 91:7]	
show_supplier.php	
    function activateSwitchery() {      [position 126:3]	
    function toggle_suppliers_add() {      [position 138:3]	
    function change_status(id, element) {      [position 152:3]	
    function submit_data() {      [position 235:3]	
    function submit_edit_save_data() {      [position 366:3]	
    function refresh_add_panel() {      [position 469:3]	
    function edit_suppliers(id, name, code, add1, add2, add3, contact, emailid) {      [position 486:3]	
    function close_add_suppliers() {      [position 512:3]	
    function add_new_suppliers() {      [position 521:3]	
show_supplier_bak.php	
    function toggle_country_add() {      [position 63:3]	
   function change_status(country_id, element) {      [position 77:2]	
    function submit_data() {       [position 162:3]	
   function submit_edit_save_data() {      [position 269:2]	
    function refresh_add_panel() {      [position 380:3]	
    function edit_country(countryid, name, code, currency) {      [position 388:3]	
    function close_add_country() {      [position 420:3]	
edit_publisher.php	
        function toggle_edit_panel() {      [position 83:7]	
        function clear_controls() {      [position 91:7]	
show_publisher.php	
    function activateSwitchery() {      [position 122:3]	
    function toggle_publisher_add() {      [position 134:3]	
    function change_status(id, element) {      [position 148:3]	
    function submit_data() {      [position 231:3]	
    function submit_edit_save_data() {      [position 361:3]	
    function refresh_add_panel() {      [position 492:3]	
    function edit_publisher(id, name, code, address1, address2, address3, contact, email) {      [position 509:3]	
    function close_add_publisher() {      [position 536:3]	
    function add_new_publisher() {      [position 545:3]